---
- name: Install and configure Go
  hosts: all
  tasks:
    - include_vars: ../vars/main.yml

    - name: Create Go installation directory
      ansible.windows.win_file:
        path: 'C:\\Install\\Go'
        state: directory

    - name: Download Go installer
      ansible.windows.win_get_url:
        url: '{{ go_installer_url }}'
        dest: 'C:\\Install\\Go\\go1.13.6.windows-amd64.msi'
        url_username: '{{ jfid }}'
        url_password: '{{ jftoken }}'
        validate_certs: false

    - name: Install Go
      ansible.windows.win_package:
        path: 'C:\\Install\\Go\\go1.13.6.windows-amd64.msi'
        state: present
        arguments:
          - /quiet
